#Method 1
#final:
#	gcc main.c add.c hello.c -o final

#Method 2
#$(CC)=gcc
#final:
#	$(CC) main.c add.c hello.c -o final
	
#Clean:
#	rm *.o final
	
#clang
all:
	clang main.c add.c hello.c -o ashwin
	gcc main.c add.c hello.c -o Ashwin

